#!/bin/bash
#
# mlCloudDetect Installation Script
#
# This script installs mlCloudDetect as a user systemd service.
# Run from the mlCloudDetect directory.
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "========================================"
echo "  mlCloudDetect Installation Script"
echo "========================================"
echo

# Get the directory where the script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "Installation directory: $SCRIPT_DIR"
echo

# Check Python version
echo -n "Checking Python version... "
if command -v python3 &> /dev/null; then
    PYTHON_VERSION=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
    PYTHON_MAJOR=$(echo "$PYTHON_VERSION" | cut -d. -f1)
    PYTHON_MINOR=$(echo "$PYTHON_VERSION" | cut -d. -f2)

    if [ "$PYTHON_MAJOR" -ge 3 ] && [ "$PYTHON_MINOR" -ge 11 ]; then
        echo -e "${GREEN}Python $PYTHON_VERSION${NC}"
    else
        echo -e "${RED}Python $PYTHON_VERSION (requires 3.11+)${NC}"
        exit 1
    fi
else
    echo -e "${RED}Python 3 not found${NC}"
    exit 1
fi

# Create virtual environment if it doesn't exist
if [ ! -d ".venv" ]; then
    echo -n "Creating virtual environment... "
    python3 -m venv .venv
    echo -e "${GREEN}done${NC}"
else
    echo -e "Virtual environment already exists: ${GREEN}.venv${NC}"
fi

# Activate virtual environment and install dependencies
echo -n "Installing dependencies... "
source .venv/bin/activate
pip install -q --upgrade pip
pip install -q -r requirements.txt
echo -e "${GREEN}done${NC}"

# Check for required files
echo
echo "Checking required files:"

if [ -f "model.onnx" ]; then
    echo -e "  model.onnx:  ${GREEN}found${NC}"
else
    echo -e "  model.onnx:  ${YELLOW}missing${NC} (required for detection)"
fi

if [ -f "labels.txt" ]; then
    echo -e "  labels.txt:  ${GREEN}found${NC}"
else
    echo -e "  labels.txt:  ${YELLOW}missing${NC} (will use defaults: Clear, Cloudy)"
fi

if [ -f "config.toml" ]; then
    echo -e "  config.toml: ${GREEN}found${NC}"
else
    echo -e "  config.toml: ${YELLOW}will be created on first run${NC}"
fi

# Install systemd service
echo
echo "Installing systemd service..."

# Create user systemd directory if it doesn't exist
mkdir -p ~/.config/systemd/user

# Generate service file with correct paths
SERVICE_FILE=~/.config/systemd/user/mlCloudDetect.service
cat > "$SERVICE_FILE" << EOF
# mlCloudDetect systemd service (auto-generated by install.sh)

[Unit]
Description=mlCloudDetect Cloud Detection Service
Documentation=https://github.com/smartc/mlCloudDetect
After=network.target

[Service]
Type=simple
Environment=PYTHONUNBUFFERED=1
WorkingDirectory=$SCRIPT_DIR
ExecStart=$SCRIPT_DIR/.venv/bin/python $SCRIPT_DIR/cloud_detect.py --daemon -q
Restart=on-failure
RestartSec=10
StandardOutput=journal
StandardError=journal
SyslogIdentifier=mlCloudDetect

[Install]
WantedBy=default.target
EOF

echo -e "  Created: ${GREEN}$SERVICE_FILE${NC}"

# Reload systemd
systemctl --user daemon-reload
echo -e "  Reloaded systemd daemon"

echo
echo "========================================"
echo -e "  ${GREEN}Installation Complete${NC}"
echo "========================================"
echo
echo "Next steps:"
echo
echo "  1. Provide required files (if not already present):"
echo "     - model.onnx  (ONNX model file)"
echo "     - labels.txt  (class labels)"
echo
echo "  2. Configure the application:"
echo "     python cloud_detect.py  # Creates default config.toml"
echo "     # Then edit config.toml with your settings"
echo
echo "  3. Test single detection:"
echo "     python cloud_detect.py -v"
echo
echo "  4. Enable and start the service:"
echo "     systemctl --user enable mlCloudDetect"
echo "     systemctl --user start mlCloudDetect"
echo
echo "  5. View service logs:"
echo "     journalctl --user -u mlCloudDetect -f"
echo
echo "  6. (Optional) Enable lingering for service to run after logout:"
echo "     sudo loginctl enable-linger \$USER"
echo
